### ISSUE TITLE
☂️ Umbrella Issue: API Reference

### ISSUE THREAD

**Issue by inyono** [edtr-io/edtr-io#210]
The following modules still need TypeDoc / JSDoc annotations to improve the automatically generated API reference (see the finished modules for examples):

- [x] @edtr-io/abstract-plugin
- [x] @edtr-io/abstract-plugin-state
- [ ] @edtr-io/core
- [ ] @edtr-io/plugin
- [ ] @edtr-io/store
- [ ] @edtr-io/ui
- [ ] @edtr-io/editor-ui
- [ ] @edtr-io/renderer-ui
