### ISSUE TITLE
☂️ Umbrella Issue: 1.0.0

### ISSUE THREAD

**Issue by inyono** [edtr-io/edtr-io#211]
Some things that need to be done before releasing 1.0.0

- [x] Plugin API for toolbar (required for 1.0.0-beta)
- [x] Plugin API for settings (required for 1.0.0-beta)
- [x] Plugin configs #147 (required for 1.0.0-beta)
- [ ] API Reference #210 (WIP: https://edtr-io.netlify.com/docs/api/)
- [ ] Documentation (WIP: https://edtr-io.netlify.com/docs/getting-started)
- [ ] i18n
- [ ] Clean up
  - [ ] Remove references to `@splish-me` (required for 1.0.0-beta)
  - [ ] Review core plugins (required for 1.0.0-beta)
  - [ ] Review plugin states (required for 1.0.0-beta)
  - [ ] Review public API (required for 1.0.0-beta)
  - [ ] Review names (required for 1.0.0-beta)
  - [ ] Review HotKeys #183
  - [x] Review `@ts-ignore` comments #182
  - [x] Resolve circular dependencies #181   
  - ...
- ...

**Comment by Entkenntnis** [comment]
most of the tasks are now overseeded in the new repo.

Only thing that is open is #183, but this is quite unspecific as well.
